### ISSUE TITLE
Why getpocket.com is in blacklist?

### ISSUE THREAD

**Issue by Magneticdud** [AdroitAdorKhan/Energized#32]
Hi, i wonder why getpocket.com is in the ultimate list - it's a website for "read later" the articles, not ads.

Plus is owned by Mozilla, so it's trustable

**Comment by AdroitAdorKhan** [comment]
Hey @Magneticdud, thanks for letting us know the issue!

Maybe it was a part of Mozilla Hardening. We will check and unblock it. Will be whitelisted from next release!

Stay Energized! ⚡

**Comment by AdroitAdorKhan** [comment]
It might have been fixed! Let us know, if you face any issue again!
