### ISSUE TITLE
ui cosmetic

### ISSUE THREAD

**Issue by foXaCe** [AdroitAdorKhan/Energized#33]
hello,

how to fix the ui bug ?
it possible to add blank.png file for replace ad image ?

![unnamed 1](https://user-images.githubusercontent.com/290678/45422044-52c4ae00-b68f-11e8-86f8-dbd89fad6c06.png)
![unnamed](https://user-images.githubusercontent.com/290678/45422045-52c4ae00-b68f-11e8-9257-f97c042cdf1b.png)

**Comment by AdroitAdorKhan** [comment]
Are you using this on Android? Then, there's no way to hide this except using third-party clients like Adguard. Because they support cosmetic filtering to hide those. (But, they are resource hungry!)

If you are on PC, then use the uBlock Origin extension in your browser. That will hide them.

**Comment by foXaCe** [comment]
yes i use the filters with Android

**Comment by AdroitAdorKhan** [comment]
Then just try a browser cache cleaning. It will hide few of them.
As hosts or any other third party resource friendly app doesn't support cosmetic filtering yet!

**Comment by foXaCe** [comment]
OK thanks for the information
