### ISSUE TITLE
Anti E.U cookies

### ISSUE THREAD

**Issue by foXaCe** [AdroitAdorKhan/Energized#34]
hello, it possible to add list for remove eu cookies ?
like this.

https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt

https://www.i-dont-care-about-cookies.eu/abp/

**Comment by AdroitAdorKhan** [comment]
Not the filters, but the domains can be added. We will check the sources you shared and add them to our list.

**Comment by foXaCe** [comment]
ok thank

**Comment by foXaCe** [comment]
more list

https://www.fanboy.co.nz/fanboy-cookiemonster.txt

**Comment by AdroitAdorKhan** [comment]
Thank you! We will check!

**Comment by AdroitAdorKhan** [comment]
We added few of them! We couldn't add all because hosts doesn't support wildcards yet!
